class CreateFormulaPinturas < ActiveRecord::Migration[5.2]
  def change
    create_table :formula_pinturas do |t|
      t.float :dolar_considerado
      t.float :formula_kg
      t.string :codigo_formula
      t.text :descripcion
      t.string :materia_prima_1
      t.float :costo_kg_materia_prima_1
      t.float :porcentaje_materia_prima_1
      t.string :kg_materia_prima_1
      t.string :costo_total_materia_prima_1
      t.string :materia_prima_2
      t.float :costo_kg_materia_prima_2
      t.float :porcentaje_materia_prima_2
      t.string :kg_materia_prima_2
      t.string :costo_total_materia_prima_2
      t.string :materia_prima_3
      t.float :costo_kg_materia_prima_3
      t.float :porcentaje_materia_prima_3
      t.string :kg_materia_prima_3
      t.string :costo_total_materia_prima_3
      t.string :materia_prima_4
      t.float :costo_kg_materia_prima_4
      t.float :porcentaje_materia_prima_4
      t.string :kg_materia_prima_4
      t.string :costo_total_materia_prima_4
      t.string :materia_prima_5
      t.float :costo_kg_materia_prima_5
      t.float :porcentaje_materia_prima_5
      t.string :kg_materia_prima_5
      t.string :costo_total_materia_prima_5
      t.string :materia_prima_6
      t.float :costo_kg_materia_prima_6
      t.float :porcentaje_materia_prima_6
      t.string :kg_materia_prima_6
      t.string :costo_total_materia_prima_6
      t.string :materia_prima_7
      t.float :costo_kg_materia_prima_7
      t.float :porcentaje_materia_prima_7
      t.string :kg_materia_prima_7
      t.string :costo_total_materia_prima_7
      t.string :materia_prima_8
      t.float :costo_kg_materia_prima_8
      t.float :porcentaje_materia_prima_8
      t.string :kg_materia_prima_8
      t.string :costo_total_materia_prima_8
      t.string :materia_prima_9
      t.float :costo_kg_materia_prima_9
      t.float :porcentaje_materia_prima_9
      t.string :kg_materia_prima_9
      t.string :costo_total_materia_prima_9
      t.string :materia_prima_10
      t.float :costo_kg_materia_prima_10
      t.float :porcentaje_materia_prima_10
      t.string :kg_materia_prima_10
      t.string :costo_total_materia_prima_10
      t.string :materia_prima_11
      t.float :costo_kg_materia_prima_11
      t.float :porcentaje_materia_prima_11
      t.string :kg_materia_prima_11
      t.string :costo_total_materia_prima_11
      t.string :materia_prima_12
      t.float :costo_kg_materia_prima_12
      t.float :porcentaje_materia_prima_12
      t.string :kg_materia_prima_12
      t.string :costo_total_materia_prima_12
      t.string :materia_prima_13
      t.float :costo_kg_materia_prima_13
      t.float :porcentaje_materia_prima_13
      t.string :kg_materia_prima_13
      t.string :costo_total_materia_prima_13
      t.string :materia_prima_14
      t.float :costo_kg_materia_prima_14
      t.float :porcentaje_materia_prima_14
      t.string :kg_materia_prima_14
      t.string :costo_total_materia_prima_14
      t.string :materia_prima_15
      t.float :costo_kg_materia_prima_15
      t.float :porcentaje_materia_prima_15
      t.string :kg_materia_prima_15
      t.string :costo_total_materia_prima_15
      t.string :materia_prima_16
      t.float :costo_kg_materia_prima_16
      t.float :porcentaje_materia_prima_16
      t.string :kg_materia_prima_16
      t.string :costo_total_materia_prima_16
      t.string :materia_prima_17
      t.float :costo_kg_materia_prima_17
      t.float :porcentaje_materia_prima_17
      t.string :kg_materia_prima_17
      t.string :costo_total_materia_prima_17
      t.string :materia_prima_18
      t.float :costo_kg_materia_prima_18
      t.float :porcentaje_materia_prima_18
      t.string :kg_materia_prima_18
      t.string :costo_total_materia_prima_18
      t.string :materia_prima_19
      t.float :costo_kg_materia_prima_19
      t.float :porcentaje_materia_prima_19
      t.string :kg_materia_prima_19
      t.string :costo_total_materia_prima_19
      t.string :materia_prima_20
      t.float :costo_kg_materia_prima_20
      t.float :porcentaje_materia_prima_20
      t.string :kg_materia_prima_20
      t.string :costo_total_materia_prima_20
      t.float :costo_final_kg

      t.timestamps
    end
  end
end
